# .streamlit/config.toml

[server]
# Set the idle timeout in seconds (default is 300 seconds / 5 minutes)
idleTimeout = 1200  # This will set the idle timeout to 10 minutes

# You can also configure other settings as needed
headless = true     # Run Streamlit in headless mode

enableCORS = false
